name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Cache dependencies and build
        uses: actions/cache@v3
        with:
          path: |
            node_modules/
            .next/cache/
          key: ${{ github.ref_name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ github.ref_name }}-
            main-

      - name: Install dependencies
        run: npm install

      - name: Build Next.js static site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
